#ifdef _WIN32
    #include <windows.h>
#endif
#include "MTester.h"
#include <strsafe.h>

#define FILL_BUFFER(buf) memset(buf, 'F', sizeof(buf))
#define SET_FIRST(buf) buf[0] = 0
#define SET_MIDDLE(buf) buf[sizeof(buf) / sizeof(buf[0]) / 2] = 0
#define SET_LAST(buf) buf[sizeof(buf) / sizeof(buf[0]) - 1] = 0

START_TEST(StringCchCopyA)
{
    char buf[8];

    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyA(buf, 0, "") != S_OK, "\n");
    mtest(strcmp(buf, "FFFFFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyA(buf, 1, "") == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyA(buf, 2, "") == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyA(buf, 3, "") == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyA(buf, 4, "") == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyA(buf, 0, "a") != S_OK, "\n");
    mtest(strcmp(buf, "FFFFFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyA(buf, 1, "a") != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyA(buf, 2, "a") == S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyA(buf, 3, "a") == S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyA(buf, 4, "a") == S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyA(buf, 0, "ab") != S_OK, "\n");
    mtest(strcmp(buf, "FFFFFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyA(buf, 1, "ab") != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyA(buf, 2, "ab") != S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyA(buf, 3, "ab") == S_OK, "\n");
    mtest(strcmp(buf, "ab") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyA(buf, 4, "ab") == S_OK, "\n");
    mtest(strcmp(buf, "ab") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyA(buf, 0, "abc") != S_OK, "\n");
    mtest(strcmp(buf, "FFFFFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyA(buf, 1, "abc") != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyA(buf, 2, "abc") != S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyA(buf, 3, "abc") != S_OK, "\n");
    mtest(strcmp(buf, "ab") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyA(buf, 4, "abc") == S_OK, "\n");
    mtest(strcmp(buf, "abc") == 0, "'%s'\n", buf);
}

START_TEST(StringCchCatA)
{
    char buf[8];

    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatA(buf, 0, "") != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatA(buf, 1, "") == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatA(buf, 2, "") == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatA(buf, 3, "") == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatA(buf, 4, "") == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatA(buf, 0, "a") != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatA(buf, 1, "a") != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatA(buf, 2, "a") == S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatA(buf, 3, "a") == S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatA(buf, 4, "a") == S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatA(buf, 0, "ab") != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatA(buf, 1, "ab") != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatA(buf, 2, "ab") != S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatA(buf, 3, "ab") == S_OK, "\n");
    mtest(strcmp(buf, "ab") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatA(buf, 4, "ab") == S_OK, "\n");
    mtest(strcmp(buf, "ab") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatA(buf, 0, "abc") != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatA(buf, 1, "abc") != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatA(buf, 2, "abc") != S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatA(buf, 3, "abc") != S_OK, "\n");
    mtest(strcmp(buf, "ab") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatA(buf, 4, "abc") == S_OK, "\n");
    mtest(strcmp(buf, "abc") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatA(buf, 0, "") != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatA(buf, 1, "") != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatA(buf, 2, "") != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatA(buf, 3, "") != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatA(buf, 4, "") != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatA(buf, 0, "a") != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatA(buf, 1, "a") != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatA(buf, 2, "a") != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatA(buf, 3, "a") != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatA(buf, 4, "a") != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatA(buf, 0, "ab") != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatA(buf, 1, "ab") != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatA(buf, 2, "ab") != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatA(buf, 3, "ab") != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatA(buf, 4, "ab") != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatA(buf, 0, "abc") != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatA(buf, 1, "abc") != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatA(buf, 2, "abc") != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatA(buf, 3, "abc") != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatA(buf, 4, "abc") != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
}

START_TEST(StringCchCatNA)
{
    char buf[8];

    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 0, "", 0) != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 1, "", 0) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 2, "", 0) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 3, "", 0) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 4, "", 0) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 0, "a", 0) != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 1, "a", 0) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 2, "a", 0) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 3, "a", 0) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 4, "a", 0) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 0, "ab", 0) != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 1, "ab", 0) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 2, "ab", 0) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 3, "ab", 0) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 4, "ab", 0) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 0, "abc", 0) != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 1, "abc", 0) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 2, "abc", 0) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 3, "abc", 0) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 4, "abc", 0) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 0, "", 1) != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 1, "", 1) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 2, "", 1) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 3, "", 1) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 4, "", 1) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 0, "a", 1) != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 1, "a", 1) != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 2, "a", 1) == S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 3, "a", 1) == S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 4, "a", 1) == S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 0, "ab", 1) != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 1, "ab", 1) != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 2, "ab", 1) == S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 3, "ab", 1) == S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 4, "ab", 1) == S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 0, "abc", 1) != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 1, "abc", 1) != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 2, "abc", 1) == S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 3, "abc", 1) == S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 4, "abc", 1) == S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 0, "", 2) != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 1, "", 2) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 2, "", 2) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 3, "", 2) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 4, "", 2) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 0, "a", 2) != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 1, "a", 2) != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 2, "a", 2) == S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 3, "a", 2) == S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 4, "a", 2) == S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 0, "ab", 2) != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 1, "ab", 2) != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 2, "ab", 2) != S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 3, "ab", 2) == S_OK, "\n");
    mtest(strcmp(buf, "ab") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 4, "ab", 2) == S_OK, "\n");
    mtest(strcmp(buf, "ab") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 0, "abc", 2) != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 1, "abc", 2) != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 2, "abc", 2) != S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 3, "abc", 2) == S_OK, "\n");
    mtest(strcmp(buf, "ab") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 4, "abc", 2) == S_OK, "\n");
    mtest(strcmp(buf, "ab") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 0, "", 3) != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 1, "", 3) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 2, "", 3) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 3, "", 3) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 4, "", 3) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 0, "a", 3) != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 1, "a", 3) != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 2, "a", 3) == S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 3, "a", 3) == S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 4, "a", 3) == S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 0, "ab", 3) != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 1, "ab", 3) != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 2, "ab", 3) != S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 3, "ab", 3) == S_OK, "\n");
    mtest(strcmp(buf, "ab") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 4, "ab", 3) == S_OK, "\n");
    mtest(strcmp(buf, "ab") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 0, "abc", 3) != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 1, "abc", 3) != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 2, "abc", 3) != S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 3, "abc", 3) != S_OK, "\n");
    mtest(strcmp(buf, "ab") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 4, "abc", 3) == S_OK, "\n");
    mtest(strcmp(buf, "abc") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 0, "", 4) != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 1, "", 4) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 2, "", 4) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 3, "", 4) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 4, "", 4) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 0, "a", 4) != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 1, "a", 4) != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 2, "a", 4) == S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 3, "a", 4) == S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 4, "a", 4) == S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 0, "ab", 4) != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 1, "ab", 4) != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 2, "ab", 4) != S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 3, "ab", 4) == S_OK, "\n");
    mtest(strcmp(buf, "ab") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 4, "ab", 4) == S_OK, "\n");
    mtest(strcmp(buf, "ab") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 0, "abc", 4) != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 1, "abc", 4) != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 2, "abc", 4) != S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 3, "abc", 4) != S_OK, "\n");
    mtest(strcmp(buf, "ab") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    mtest(StringCchCatNA(buf, 4, "abc", 4) == S_OK, "\n");
    mtest(strcmp(buf, "abc") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 0, "", 0) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 1, "", 0) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 2, "", 0) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 3, "", 0) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 4, "", 0) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 0, "a", 0) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 1, "a", 0) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 2, "a", 0) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 3, "a", 0) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 4, "a", 0) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 0, "ab", 0) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 1, "ab", 0) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 2, "ab", 0) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 3, "ab", 0) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 4, "ab", 0) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 0, "abc", 0) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 1, "abc", 0) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 2, "abc", 0) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 3, "abc", 0) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 4, "abc", 0) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 0, "", 1) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 1, "", 1) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 2, "", 1) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 3, "", 1) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 4, "", 1) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 0, "a", 1) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 1, "a", 1) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 2, "a", 1) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 3, "a", 1) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 4, "a", 1) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 0, "ab", 1) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 1, "ab", 1) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 2, "ab", 1) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 3, "ab", 1) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 4, "ab", 1) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 0, "abc", 1) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 1, "abc", 1) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 2, "abc", 1) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 3, "abc", 1) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 4, "abc", 1) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 0, "", 2) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 1, "", 2) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 2, "", 2) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 3, "", 2) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 4, "", 2) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 0, "a", 2) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 1, "a", 2) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 2, "a", 2) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 3, "a", 2) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 4, "a", 2) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 0, "ab", 2) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 1, "ab", 2) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 2, "ab", 2) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 3, "ab", 2) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 4, "ab", 2) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 0, "abc", 2) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 1, "abc", 2) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 2, "abc", 2) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 3, "abc", 2) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 4, "abc", 2) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 0, "", 3) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 1, "", 3) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 2, "", 3) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 3, "", 3) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 4, "", 3) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 0, "a", 3) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 1, "a", 3) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 2, "a", 3) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 3, "a", 3) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 4, "a", 3) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 0, "ab", 3) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 1, "ab", 3) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 2, "ab", 3) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 3, "ab", 3) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 4, "ab", 3) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 0, "abc", 3) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 1, "abc", 3) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 2, "abc", 3) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 3, "abc", 3) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 4, "abc", 3) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 0, "", 4) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 1, "", 4) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 2, "", 4) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 3, "", 4) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 4, "", 4) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 0, "a", 4) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 1, "a", 4) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 2, "a", 4) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 3, "a", 4) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 4, "a", 4) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 0, "ab", 4) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 1, "ab", 4) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 2, "ab", 4) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 3, "ab", 4) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 4, "ab", 4) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 0, "abc", 4) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 1, "abc", 4) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 2, "abc", 4) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 3, "abc", 4) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    mtest(StringCchCatNA(buf, 4, "abc", 4) != S_OK, "\n");
    mtest(strcmp(buf, "FFFF") == 0, "'%s'\n", buf);
}

START_TEST(StringCchCopyNA)
{
    char buf[8];

    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 0, "", 0) != S_OK, "\n");
    mtest(strcmp(buf, "FFFFFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 1, "", 0) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 2, "", 0) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 3, "", 0) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 4, "", 0) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 0, "a", 0) != S_OK, "\n");
    mtest(strcmp(buf, "FFFFFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 1, "a", 0) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 2, "a", 0) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 3, "a", 0) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 4, "a", 0) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 0, "ab", 0) != S_OK, "\n");
    mtest(strcmp(buf, "FFFFFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 1, "ab", 0) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 2, "ab", 0) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 3, "ab", 0) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 4, "ab", 0) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 0, "abc", 0) != S_OK, "\n");
    mtest(strcmp(buf, "FFFFFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 1, "abc", 0) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 2, "abc", 0) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 3, "abc", 0) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 4, "abc", 0) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 0, "", 1) != S_OK, "\n");
    mtest(strcmp(buf, "FFFFFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 1, "", 1) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 2, "", 1) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 3, "", 1) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 4, "", 1) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 0, "a", 1) != S_OK, "\n");
    mtest(strcmp(buf, "FFFFFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 1, "a", 1) != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 2, "a", 1) == S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 3, "a", 1) == S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 4, "a", 1) == S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 0, "ab", 1) != S_OK, "\n");
    mtest(strcmp(buf, "FFFFFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 1, "ab", 1) != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 2, "ab", 1) == S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 3, "ab", 1) == S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 4, "ab", 1) == S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 0, "abc", 1) != S_OK, "\n");
    mtest(strcmp(buf, "FFFFFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 1, "abc", 1) != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 2, "abc", 1) == S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 3, "abc", 1) == S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 4, "abc", 1) == S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 0, "", 2) != S_OK, "\n");
    mtest(strcmp(buf, "FFFFFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 1, "", 2) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 2, "", 2) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 3, "", 2) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 4, "", 2) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 0, "a", 2) != S_OK, "\n");
    mtest(strcmp(buf, "FFFFFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 1, "a", 2) != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 2, "a", 2) == S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 3, "a", 2) == S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 4, "a", 2) == S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 0, "ab", 2) != S_OK, "\n");
    mtest(strcmp(buf, "FFFFFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 1, "ab", 2) != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 2, "ab", 2) != S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 3, "ab", 2) == S_OK, "\n");
    mtest(strcmp(buf, "ab") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 4, "ab", 2) == S_OK, "\n");
    mtest(strcmp(buf, "ab") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 0, "abc", 2) != S_OK, "\n");
    mtest(strcmp(buf, "FFFFFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 1, "abc", 2) != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 2, "abc", 2) != S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 3, "abc", 2) == S_OK, "\n");
    mtest(strcmp(buf, "ab") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 4, "abc", 2) == S_OK, "\n");
    mtest(strcmp(buf, "ab") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 0, "", 3) != S_OK, "\n");
    mtest(strcmp(buf, "FFFFFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 1, "", 3) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 2, "", 3) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 3, "", 3) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 4, "", 3) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 0, "a", 3) != S_OK, "\n");
    mtest(strcmp(buf, "FFFFFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 1, "a", 3) != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 2, "a", 3) == S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 3, "a", 3) == S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 4, "a", 3) == S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 0, "ab", 3) != S_OK, "\n");
    mtest(strcmp(buf, "FFFFFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 1, "ab", 3) != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 2, "ab", 3) != S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 3, "ab", 3) == S_OK, "\n");
    mtest(strcmp(buf, "ab") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 4, "ab", 3) == S_OK, "\n");
    mtest(strcmp(buf, "ab") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 0, "abc", 3) != S_OK, "\n");
    mtest(strcmp(buf, "FFFFFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 1, "abc", 3) != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 2, "abc", 3) != S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 3, "abc", 3) != S_OK, "\n");
    mtest(strcmp(buf, "ab") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 4, "abc", 3) == S_OK, "\n");
    mtest(strcmp(buf, "abc") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 0, "", 4) != S_OK, "\n");
    mtest(strcmp(buf, "FFFFFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 1, "", 4) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 2, "", 4) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 3, "", 4) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 4, "", 4) == S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 0, "a", 4) != S_OK, "\n");
    mtest(strcmp(buf, "FFFFFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 1, "a", 4) != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 2, "a", 4) == S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 3, "a", 4) == S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 4, "a", 4) == S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 0, "ab", 4) != S_OK, "\n");
    mtest(strcmp(buf, "FFFFFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 1, "ab", 4) != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 2, "ab", 4) != S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 3, "ab", 4) == S_OK, "\n");
    mtest(strcmp(buf, "ab") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 4, "ab", 4) == S_OK, "\n");
    mtest(strcmp(buf, "ab") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 0, "abc", 4) != S_OK, "\n");
    mtest(strcmp(buf, "FFFFFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 1, "abc", 4) != S_OK, "\n");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 2, "abc", 4) != S_OK, "\n");
    mtest(strcmp(buf, "a") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 3, "abc", 4) != S_OK, "\n");
    mtest(strcmp(buf, "ab") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    mtest(StringCchCopyNA(buf, 4, "abc", 4) == S_OK, "\n");
    mtest(strcmp(buf, "abc") == 0, "'%s'\n", buf);
}

START_TEST(StringCchPrintfA)
{
    char buf[8];

    FILL_BUFFER(buf);
    SET_LAST(buf);
    StringCchPrintfA(buf, 0, "%d", 1234);
    mtest(strcmp(buf, "FFFFFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    StringCchPrintfA(buf, 1, "%d", 1234);
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    StringCchPrintfA(buf, 2, "%d", 1234);
    mtest(strcmp(buf, "1") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    StringCchPrintfA(buf, 3, "%d", 1234);
    mtest(strcmp(buf, "12") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    StringCchPrintfA(buf, 4, "%d", 1234);
    mtest(strcmp(buf, "123") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    StringCchPrintfA(buf, 5, "%d", 1234);
    mtest(strcmp(buf, "1234") == 0, "'%s'\n", buf);

    FILL_BUFFER(buf);
    SET_LAST(buf);
    StringCchPrintfA(buf, 0, "%s", "1234");
    mtest(strcmp(buf, "FFFFFFF") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    StringCchPrintfA(buf, 1, "%s", "1234");
    mtest(strcmp(buf, "") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    StringCchPrintfA(buf, 2, "%s", "1234");
    mtest(strcmp(buf, "1") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    StringCchPrintfA(buf, 3, "%s", "1234");
    mtest(strcmp(buf, "12") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    StringCchPrintfA(buf, 4, "%s", "1234");
    mtest(strcmp(buf, "123") == 0, "'%s'\n", buf);
    FILL_BUFFER(buf);
    SET_LAST(buf);
    StringCchPrintfA(buf, 5, "%s", "1234");
    mtest(strcmp(buf, "1234") == 0, "'%s'\n", buf);
}


START_TEST(StringCchLengthA)
{
    size_t cch;

    mtest(StringCchLengthA("", 0, &cch) != S_OK, "\n");
    mtest(cch == 0, "%d\n", (int)cch);
    mtest(StringCchLengthA("", 1, &cch) == S_OK, "\n");
    mtest(cch == 0, "%d\n", (int)cch);
    mtest(StringCchLengthA("", 2, &cch) == S_OK, "\n");
    mtest(cch == 0, "%d\n", (int)cch);
    mtest(StringCchLengthA("", 3, &cch) == S_OK, "\n");
    mtest(cch == 0, "%d\n", (int)cch);

    mtest(StringCchLengthA("a", 0, &cch) != S_OK, "\n");
    mtest(cch == 0, "%d\n", (int)cch);
    mtest(StringCchLengthA("a", 1, &cch) != S_OK, "\n");
    mtest(cch == 0, "%d\n", (int)cch);
    mtest(StringCchLengthA("a", 2, &cch) == S_OK, "\n");
    mtest(cch == 1, "%d\n", (int)cch);
    mtest(StringCchLengthA("a", 3, &cch) == S_OK, "\n");
    mtest(cch == 1, "%d\n", (int)cch);

    mtest(StringCchLengthA("ab", 0, &cch) != S_OK, "\n");
    mtest(cch == 0, "%d\n", (int)cch);
    mtest(StringCchLengthA("ab", 1, &cch) != S_OK, "\n");
    mtest(cch == 0, "%d\n", (int)cch);
    mtest(StringCchLengthA("ab", 2, &cch) != S_OK, "\n");
    mtest(cch == 0, "%d\n", (int)cch);
    mtest(StringCchLengthA("ab", 3, &cch) == S_OK, "\n");
    mtest(cch == 2, "%d\n", (int)cch);

    mtest(StringCchLengthA("abc", 0, &cch) != S_OK, "\n");
    mtest(cch == 0, "%d\n", (int)cch);
    mtest(StringCchLengthA("abc", 1, &cch) != S_OK, "\n");
    mtest(cch == 0, "%d\n", (int)cch);
    mtest(StringCchLengthA("abc", 2, &cch) != S_OK, "\n");
    mtest(cch == 0, "%d\n", (int)cch);
    mtest(StringCchLengthA("abc", 3, &cch) != S_OK, "\n");
    mtest(cch == 0, "%d\n", (int)cch);

    mtest(StringCchLengthA("abcd", 0, &cch) != S_OK, "\n");
    mtest(cch == 0, "%d\n", (int)cch);
    mtest(StringCchLengthA("abcd", 1, &cch) != S_OK, "\n");
    mtest(cch == 0, "%d\n", (int)cch);
    mtest(StringCchLengthA("abcd", 2, &cch) != S_OK, "\n");
    mtest(cch == 0, "%d\n", (int)cch);
    mtest(StringCchLengthA("abcd", 3, &cch) != S_OK, "\n");
    mtest(cch == 0, "%d\n", (int)cch);
}

BEGIN_TESTS()
    DEFINE_TEST(StringCchCopyA)
    DEFINE_TEST(StringCchCatA)
    DEFINE_TEST(StringCchCatNA)
    DEFINE_TEST(StringCchCopyNA)
    DEFINE_TEST(StringCchPrintfA)
    DEFINE_TEST(StringCchLengthA)
END_TESTS()
