#define BUFSIZE 8
#define FILL_BUFFER(buf) memset(buf, 'F', sizeof(buf))
#define SET_FIRST(buf) buf[0] = 0
#define SET_MIDDLE(buf) buf[BUFSIZE / 2] = 0
#define SET_LAST(buf) buf[BUFSIZE - 1] = 0

START_TEST(StringCchCopyA)
{
    char buf[BUFSIZE];
    HRESULT hr;

    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyA(buf, 0, "");
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFFFFF");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyA(buf, 1, "");
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyA(buf, 2, "");
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyA(buf, 3, "");
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyA(buf, 4, "");
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");

    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyA(buf, 0, "a");
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFFFFF");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyA(buf, 1, "a");
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyA(buf, 2, "a");
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "a");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyA(buf, 3, "a");
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "a");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyA(buf, 4, "a");
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "a");

    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyA(buf, 0, "ab");
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFFFFF");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyA(buf, 1, "ab");
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyA(buf, 2, "ab");
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "a");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyA(buf, 3, "ab");
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "ab");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyA(buf, 4, "ab");
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "ab");

    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyA(buf, 0, "abc");
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFFFFF");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyA(buf, 1, "abc");
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyA(buf, 2, "abc");
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "a");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyA(buf, 3, "abc");
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "ab");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyA(buf, 4, "abc");
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "abc");
}

START_TEST(StringCchCatA)
{
    char buf[BUFSIZE];
    HRESULT hr;

    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatA(buf, 0, "");
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatA(buf, 1, "");
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatA(buf, 2, "");
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatA(buf, 3, "");
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatA(buf, 4, "");
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");

    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatA(buf, 0, "a");
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatA(buf, 1, "a");
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatA(buf, 2, "a");
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "a");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatA(buf, 3, "a");
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "a");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatA(buf, 4, "a");
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "a");

    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatA(buf, 0, "ab");
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatA(buf, 1, "ab");
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatA(buf, 2, "ab");
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "a");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatA(buf, 3, "ab");
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "ab");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatA(buf, 4, "ab");
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "ab");

    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatA(buf, 0, "abc");
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatA(buf, 1, "abc");
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatA(buf, 2, "abc");
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "a");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatA(buf, 3, "abc");
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "ab");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatA(buf, 4, "abc");
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "abc");

    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatA(buf, 0, "");
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatA(buf, 1, "");
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatA(buf, 2, "");
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatA(buf, 3, "");
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatA(buf, 4, "");
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");

    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatA(buf, 0, "a");
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatA(buf, 1, "a");
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatA(buf, 2, "a");
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatA(buf, 3, "a");
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatA(buf, 4, "a");
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");

    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatA(buf, 0, "ab");
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatA(buf, 1, "ab");
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatA(buf, 2, "ab");
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatA(buf, 3, "ab");
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatA(buf, 4, "ab");
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");

    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatA(buf, 0, "abc");
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatA(buf, 1, "abc");
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatA(buf, 2, "abc");
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatA(buf, 3, "abc");
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatA(buf, 4, "abc");
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
}

START_TEST(StringCchCatNA)
{
    char buf[BUFSIZE];
    HRESULT hr;

    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 0, "", 0);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 1, "", 0);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 2, "", 0);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 3, "", 0);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 4, "", 0);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");

    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 0, "a", 0);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 1, "a", 0);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 2, "a", 0);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 3, "a", 0);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 4, "a", 0);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");

    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 0, "ab", 0);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 1, "ab", 0);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 2, "ab", 0);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 3, "ab", 0);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 4, "ab", 0);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");

    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 0, "abc", 0);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER );
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 1, "abc", 0);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 2, "abc", 0);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 3, "abc", 0);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 4, "abc", 0);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");

    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 0, "", 1);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 1, "", 1);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 2, "", 1);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 3, "", 1);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 4, "", 1);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");

    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 0, "a", 1);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 1, "a", 1);
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 2, "a", 1);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "a");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 3, "a", 1);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "a");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 4, "a", 1);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "a");

    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 0, "ab", 1);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 1, "ab", 1);
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 2, "ab", 1);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "a");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 3, "ab", 1);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "a");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 4, "ab", 1);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "a");

    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 0, "abc", 1);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 1, "abc", 1);
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 2, "abc", 1);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "a");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 3, "abc", 1);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "a");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 4, "abc", 1);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "a");

    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 0, "", 2);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 1, "", 2);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 2, "", 2);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 3, "", 2);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 4, "", 2);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");

    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 0, "a", 2);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 1, "a", 2);
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 2, "a", 2);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "a");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 3, "a", 2);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "a");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 4, "a", 2);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "a");

    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 0, "ab", 2);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 1, "ab", 2);
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 2, "ab", 2);
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "a");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 3, "ab", 2);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "ab");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 4, "ab", 2);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "ab");

    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 0, "abc", 2);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 1, "abc", 2);
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 2, "abc", 2);
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "a");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 3, "abc", 2);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "ab");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 4, "abc", 2);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "ab");

    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 0, "", 3);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 1, "", 3);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 2, "", 3);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 3, "", 3);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 4, "", 3);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");

    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 0, "a", 3);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 1, "a", 3);
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 2, "a", 3);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "a");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 3, "a", 3);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "a");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 4, "a", 3);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "a");

    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 0, "ab", 3);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 1, "ab", 3);
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 2, "ab", 3);
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "a");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 3, "ab", 3);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "ab");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 4, "ab", 3);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "ab");

    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 0, "abc", 3);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 1, "abc", 3);
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 2, "abc", 3);
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "a");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 3, "abc", 3);
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "ab");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 4, "abc", 3);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "abc");

    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 0, "", 4);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 1, "", 4);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 2, "", 4);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 3, "", 4);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 4, "", 4);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");

    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 0, "a", 4);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 1, "a", 4);
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 2, "a", 4);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "a");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 3, "a", 4);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "a");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 4, "a", 4);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "a");

    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 0, "ab", 4);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 1, "ab", 4);
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 2, "ab", 4);
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "a");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 3, "ab", 4);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "ab");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 4, "ab", 4);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "ab");

    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 0, "abc", 4);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 1, "abc", 4);
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 2, "abc", 4);
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "a");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 3, "abc", 4);
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "ab");
    FILL_BUFFER(buf);
    SET_FIRST(buf);
    hr = StringCchCatNA(buf, 4, "abc", 4);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "abc");

    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 0, "", 0);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 1, "", 0);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 2, "", 0);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 3, "", 0);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 4, "", 0);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");

    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 0, "a", 0);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 1, "a", 0);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 2, "a", 0);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 3, "a", 0);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 4, "a", 0);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");

    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 0, "ab", 0);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 1, "ab", 0);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 2, "ab", 0);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 3, "ab", 0);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 4, "ab", 0);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");

    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 0, "abc", 0);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 1, "abc", 0);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 2, "abc", 0);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 3, "abc", 0);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 4, "abc", 0);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");

    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 0, "", 1);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 1, "", 1);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 2, "", 1);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 3, "", 1);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 4, "", 1);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");

    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 0, "a", 1);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 1, "a", 1);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 2, "a", 1);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 3, "a", 1);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 4, "a", 1);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");

    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 0, "ab", 1);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 1, "ab", 1);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 2, "ab", 1);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 3, "ab", 1);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 4, "ab", 1);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");

    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 0, "abc", 1);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 1, "abc", 1);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 2, "abc", 1);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 3, "abc", 1);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 4, "abc", 1);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");

    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 0, "", 2);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 1, "", 2);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 2, "", 2);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 3, "", 2);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 4, "", 2);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");

    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 0, "a", 2);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 1, "a", 2);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 2, "a", 2);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 3, "a", 2);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 4, "a", 2);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");

    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 0, "ab", 2);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 1, "ab", 2);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 2, "ab", 2);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 3, "ab", 2);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 4, "ab", 2);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");

    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 0, "abc", 2);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 1, "abc", 2);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 2, "abc", 2);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 3, "abc", 2);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 4, "abc", 2);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");

    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 0, "", 3);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 1, "", 3);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 2, "", 3);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 3, "", 3);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 4, "", 3);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");

    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 0, "a", 3);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 1, "a", 3);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 2, "a", 3);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 3, "a", 3);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 4, "a", 3);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");

    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 0, "ab", 3);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 1, "ab", 3);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 2, "ab", 3);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 3, "ab", 3);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 4, "ab", 3);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");

    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 0, "abc", 3);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 1, "abc", 3);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 2, "abc", 3);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 3, "abc", 3);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 4, "abc", 3);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");

    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 0, "", 4);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 1, "", 4);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 2, "", 4);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 3, "", 4);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 4, "", 4);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");

    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 0, "a", 4);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 1, "a", 4);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 2, "a", 4);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 3, "a", 4);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 4, "a", 4);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");

    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 0, "ab", 4);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 1, "ab", 4);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 2, "ab", 4);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 3, "ab", 4);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 4, "ab", 4);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");

    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 0, "abc", 4);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 1, "abc", 4);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 2, "abc", 4);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 3, "abc", 4);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
    FILL_BUFFER(buf);
    SET_MIDDLE(buf);
    hr = StringCchCatNA(buf, 4, "abc", 4);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFF");
}

START_TEST(StringCchCopyNA)
{
    char buf[BUFSIZE];
    HRESULT hr;

    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 0, "", 0);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFFFFF");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 1, "", 0);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 2, "", 0);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 3, "", 0);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 4, "", 0);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");

    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 0, "a", 0);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFFFFF");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 1, "a", 0);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 2, "a", 0);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 3, "a", 0);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 4, "a", 0);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");

    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 0, "ab", 0);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFFFFF");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 1, "ab", 0);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 2, "ab", 0);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 3, "ab", 0);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 4, "ab", 0);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");

    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 0, "abc", 0);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFFFFF");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 1, "abc", 0);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 2, "abc", 0);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 3, "abc", 0);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 4, "abc", 0);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");

    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 0, "", 1);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFFFFF");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 1, "", 1);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 2, "", 1);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 3, "", 1);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 4, "", 1);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");

    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 0, "a", 1);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFFFFF");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 1, "a", 1);
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 2, "a", 1);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "a");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 3, "a", 1);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "a");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 4, "a", 1);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "a");

    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 0, "ab", 1);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFFFFF");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 1, "ab", 1);
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 2, "ab", 1);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "a");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 3, "ab", 1);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "a");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 4, "ab", 1);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "a");

    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 0, "abc", 1);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFFFFF");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 1, "abc", 1);
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 2, "abc", 1);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "a");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 3, "abc", 1);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "a");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 4, "abc", 1);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "a");

    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 0, "", 2);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFFFFF");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 1, "", 2);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 2, "", 2);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 3, "", 2);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 4, "", 2);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");

    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 0, "a", 2);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFFFFF");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 1, "a", 2);
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 2, "a", 2);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "a");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 3, "a", 2);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "a");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 4, "a", 2);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "a");

    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 0, "ab", 2);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFFFFF");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 1, "ab", 2);
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 2, "ab", 2);
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "a");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 3, "ab", 2);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "ab");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 4, "ab", 2);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "ab");

    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 0, "abc", 2);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFFFFF");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 1, "abc", 2);
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 2, "abc", 2);
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "a");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 3, "abc", 2);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "ab");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 4, "abc", 2);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "ab");

    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 0, "", 3);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFFFFF");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 1, "", 3);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 2, "", 3);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 3, "", 3);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 4, "", 3);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");

    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 0, "a", 3);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFFFFF");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 1, "a", 3);
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 2, "a", 3);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "a");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 3, "a", 3);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "a");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 4, "a", 3);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "a");

    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 0, "ab", 3);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFFFFF");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 1, "ab", 3);
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 2, "ab", 3);
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "a");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 3, "ab", 3);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "ab");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 4, "ab", 3);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "ab");

    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 0, "abc", 3);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFFFFF");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 1, "abc", 3);
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 2, "abc", 3);
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "a");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 3, "abc", 3);
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "ab");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 4, "abc", 3);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "abc");

    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 0, "", 4);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFFFFF");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 1, "", 4);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 2, "", 4);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 3, "", 4);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 4, "", 4);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "");

    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 0, "a", 4);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFFFFF");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 1, "a", 4);
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 2, "a", 4);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "a");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 3, "a", 4);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "a");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 4, "a", 4);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "a");

    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 0, "ab", 4);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFFFFF");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 1, "ab", 4);
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 2, "ab", 4);
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "a");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 3, "ab", 4);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "ab");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 4, "ab", 4);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "ab");

    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 0, "abc", 4);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFFFFF");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 1, "abc", 4);
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 2, "abc", 4);
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "a");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 3, "abc", 4);
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "ab");
    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchCopyNA(buf, 4, "abc", 4);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "abc");
}

START_TEST(StringCchPrintfA)
{
    char buf[BUFSIZE];
    HRESULT hr;

    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchPrintfA(buf, 0, "%d", 1234);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFFFFF");

    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchPrintfA(buf, 1, "%d", 1234);
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "");

    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchPrintfA(buf, 2, "%d", 1234);
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "1");

    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchPrintfA(buf, 3, "%d", 1234);
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "12");

    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchPrintfA(buf, 4, "%d", 1234);
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "123");

    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchPrintfA(buf, 5, "%d", 1234);
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "1234");

    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchPrintfA(buf, 0, "%s", "1234");
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest_psz_eq(buf, "FFFFFFF");

    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchPrintfA(buf, 1, "%s", "1234");
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "");

    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchPrintfA(buf, 2, "%s", "1234");
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "1");

    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchPrintfA(buf, 3, "%s", "1234");
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "12");

    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchPrintfA(buf, 4, "%s", "1234");
    mtest_long_eq(hr, STRSAFE_E_INSUFFICIENT_BUFFER);
    mtest_psz_eq(buf, "123");

    FILL_BUFFER(buf);
    SET_LAST(buf);
    hr = StringCchPrintfA(buf, 5, "%s", "1234");
    mtest_long_eq(hr, S_OK);
    mtest_psz_eq(buf, "1234");
}


START_TEST(StringCchLengthA)
{
    size_t cch;
    HRESULT hr;

    cch = 123;
    hr = StringCchLengthA("", 0, &cch);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest(cch == 0, "%d\n", (int)cch);
    cch = 123;
    hr = StringCchLengthA("", 1, &cch);
    mtest_long_eq(hr, S_OK);
    mtest(cch == 0, "%d\n", (int)cch);
    cch = 123;
    hr = StringCchLengthA("", 2, &cch);
    mtest_long_eq(hr, S_OK);
    mtest(cch == 0, "%d\n", (int)cch);
    cch = 123;
    hr = StringCchLengthA("", 3, &cch);
    mtest_long_eq(hr, S_OK);
    mtest(cch == 0, "%d\n", (int)cch);

    cch = 123;
    hr = StringCchLengthA("a", 0, &cch);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest(cch == 0, "%d\n", (int)cch);
    cch = 123;
    hr = StringCchLengthA("a", 1, &cch);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest(cch == 0, "%d\n", (int)cch);
    cch = 123;
    hr = StringCchLengthA("a", 2, &cch);
    mtest_long_eq(hr, S_OK);
    mtest(cch == 1, "%d\n", (int)cch);
    cch = 123;
    hr = StringCchLengthA("a", 3, &cch);
    mtest_long_eq(hr, S_OK);
    mtest(cch == 1, "%d\n", (int)cch);

    cch = 123;
    hr = StringCchLengthA("ab", 0, &cch);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest(cch == 0, "%d\n", (int)cch);
    cch = 123;
    hr = StringCchLengthA("ab", 1, &cch);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest(cch == 0, "%d\n", (int)cch);
    cch = 123;
    hr = StringCchLengthA("ab", 2, &cch);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest(cch == 0, "%d\n", (int)cch);
    cch = 123;
    hr = StringCchLengthA("ab", 3, &cch);
    mtest_long_eq(hr, S_OK);
    mtest(cch == 2, "%d\n", (int)cch);

    cch = 123;
    hr = StringCchLengthA("abc", 0, &cch);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest(cch == 0, "%d\n", (int)cch);
    cch = 123;
    hr = StringCchLengthA("abc", 1, &cch);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest(cch == 0, "%d\n", (int)cch);
    cch = 123;
    hr = StringCchLengthA("abc", 2, &cch);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest(cch == 0, "%d\n", (int)cch);
    cch = 123;
    hr = StringCchLengthA("abc", 3, &cch);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest(cch == 0, "%d\n", (int)cch);

    cch = 123;
    hr = StringCchLengthA("abcd", 0, &cch);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest(cch == 0, "%d\n", (int)cch);
    cch = 123;
    hr = StringCchLengthA("abcd", 1, &cch);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest(cch == 0, "%d\n", (int)cch);
    cch = 123;
    hr = StringCchLengthA("abcd", 2, &cch);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest(cch == 0, "%d\n", (int)cch);
    cch = 123;
    hr = StringCchLengthA("abcd", 3, &cch);
    mtest_long_eq(hr, STRSAFE_E_INVALID_PARAMETER);
    mtest(cch == 0, "%d\n", (int)cch);
}

BEGIN_TESTS()
    DEFINE_TEST(StringCchCatA)
    DEFINE_TEST(StringCchCatNA)
    DEFINE_TEST(StringCchCopyA)
    DEFINE_TEST(StringCchCopyNA)
    DEFINE_TEST(StringCchLengthA)
    DEFINE_TEST(StringCchPrintfA)
END_TESTS()
